<?php

namespace Api\SymfBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsRepository extends \Doctrine\ORM\EntityRepository
{
	public function countByName() {
 
 return $this->createQueryBuilder('e')
 
                        ->select('COUNT(e)')

                        ->groupBy('e.name')
 
                        ->getQuery()
 
                        ->getResult();
 
        //  $em = $this->getDoctrine()->getManager();
        //  $query = $em->createQuery(
        // "SELECT Name, COUNT(*) FROM ApiSymfBundle:Events GROUP BY Name"
        // );
        //  $events = $query->getResult();

// $qb = $this->createQueryBuilder('e')
// 				   ->join('e.name', 'n')
// 				   ->select('COUNT(n)') 
// 				   ->groupBy('e.id');
//  return $this

// ->createQueryBuilder('e')
// ->getQuery()
// ->getResult();

		
 
    }
}
